# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog
tagline:          Making data science more efficient
url:              https://datacarpentry.github.io
paginate:         1
baseurl:          /blog
author:
  name:           Data Carpentry contributors
  url:            http://datacarpentry.org
  email:          admin@datacarpentry.org

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/datacarpentry/blog

pages_list:       
  About: 'about'
  Archive: 'archive'
  Feed: 'atom.atom'
