# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Data Carpentry
tagline:          Making data science more efficient
url:              http://datacarpentry.org
paginate:         1
baseurl:          /
author:
  name:           Data Carpentry contributors
  url:            https://twitter.com/datacarpentry
  email:          admin@datacarpentry.org

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/datacarpentry/blog

pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.atom'